### ISSUE TITLE
Connected icon

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#39]
When motherlover is connected to a PS server the icon should be different.
Also, I was thinking about opening the browser automatically, @timriot ?

**Comment by timriot** [comment]
Opening the browser automatically would be awesome, so long as there isn't a significant lag when loading PSDs for the first time, as we saw in the test we performed. If there is a lag, would it be possible to launch the browser without bringing the window forward, so that the loading process could begin without making it clear that there is a lag?
