### ISSUE TITLE
Work on some sort of TypeKit integration

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#57]

**Comment by kilianc** [comment]
I am working on some kind of artificial OAuth since TypeKit doesn't provide it (for now).
I did it, but I am not sure it is the right approach. At the end of the day people will store they tokens inside their configuration files...

A token copy paste from your typekit account imho is the right way.
We can use mac keychain to store it.

The other way is to ask for username/password every time generator starts. I already successfully coded the scraper:

![](http://f.cl.ly/items/1D160g1f3K043j0U182x/Screen%20Shot%202012-10-11%20at%2010.59.43%20AM.png)

username and password are hardcoded here, but we can prompt them.

[TypeKit API](https://typekit.com/docs/api) covers all we need to embed it in generator.

**Comment by timriot** [comment]
This is quite exciting! Can you look into how auth tokens are stored on Windows (ick, I know)?

**Comment by timriot** [comment]
Followed up with Typekit engineering manager, Ryan Carver, to provide status, hook him up with Kilian, etc. Meeting with Jeff Veen tentatively scheduled for Thursday of next week.

**Comment by timriot** [comment]
Spoken with the TypeKit guys. They are into the idea of using a browser extension to add TypeKit support. Need to follow up with Kristofer re: this.

**Comment by timriot** [comment]
Email sent. Waiting to hear back.

**Comment by timriot** [comment]
TypeKit will be releasing a desktop application, which will make TK fonts available to all applications on the local system. ML will get access to these fonts for free.

**Comment by timriot** [comment]
closing because this is happening outside of the scope of ML.
